# .github/workflows/nodejs-ci.yml
name: Node.js CI

on:
  push:
    branches:
      - dd1125
  pull_request:
    branches:
      - dd1125

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v3

    - name: Node.js 설정
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: 종속성 설치
      run: npm install

    - name: 빌드 수행
      run: npm run build

    - name: 테스트 실행
      run: npm test
