name: Merge dd1125 to version2

on:
  workflow_dispatch:
    inputs:
      base:
        description: 'Base branch to merge into (default: version2)'
        required: false
        default: 'version2'
      head:
        description: 'Branch to merge from (default: dd1125)'
        required: false
        default: 'dd1125'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge dd1125 into version2
        run: |
          git checkout ${{ inputs.base }}
          git merge --no-ff ${{ inputs.head }}
          git push origin ${{ inputs.base }}
